name: prnyai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.1.0
  carousel_slider: ^4.2.1
  location: ^5.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  webview_flutter: ^3.0.4
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  file_picker: ^4.0.10
  sticky_headers: ^0.3.0+2
  provider: ^6.1.1
  flutter_pdfview: ^1.3.2
  photo_view: ^0.14.0
  data_tables: ^1.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
