import 'package:flutter/material.dart';

class CCTNSDatabaseScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    List<String> indianNames = [
      'Aarav',
      'Aanya',
      'Arjun',
      'Anaya',
      'Advait',
      'Avni',
      'Aryan',
      'Amara',
      'Advika',
      'Aaryan',
      'Aadhya',
      'Ayaan',
      'Anika',
      'Ahaan',
      'Aaradhya',
      'Vihaan',
      'Myra',
      'Reyansh',
      'Saisha',
      'Abeer',
      'Anvi',
      'Arnav',
      'Zara',
      'Arush',
      'Aisha',
      'Ishaan',
      'Riya',
      'Vivaan',
      'Ishita',
      'Kabir',
      'Nia',
      'Kiaan',
      'Zoya',
      'Aarush',
      'Avisha',
      'Aarush',
      'Anaya',
      'Aarav',
      'Aarna',
      'Reva',
      'Shaurya',
      'Ira',
      'Veer',
      'Anaya',
      'Kian',
      'Gia',
      'Kabir',
      'Ritara',
      'Arjun',
      'Arjun',
    ];

    List<String> rajasthanDistricts = [
      'Jaipur Urban (Jaipur)',
      'Jaipur Rural (Jaipur)',
      'Kekri (Ajmer)',
      'Sanchore (Jalore)',
      'Khairthal (Alwar)',
      'Anupgarh (Sriganganagar)',
      'Gangapur City (Sawai Madhopur)',
      'Neem ka thana (Sikar)',
      'Phalodi (Jodhpur)',
      'Dudu (Jaipur)',
      'Beawar (Ajmer)',
      'Didwana-Kuchaman (Nagaur)',
      'Salumber (Udaipur)',
      'Shahpura (Bhilwara)',
      'Jodhpur Urban (Jodhpur)',
      'Jodhpur Rural (Jodhpur)',
      'Balotra (Barmer)',
      'Deeg (Bharatpur)',
      'Jaipur Urban (Jaipur)',
      'Jaipur Rural (Jaipur)',
      'Kekri (Ajmer)',
      'Sanchore (Jalore)',
      'Khairthal (Alwar)',
      'Anupgarh (Sriganganagar)',
      'Gangapur City (Sawai Madhopur)',
      'Neem ka thana (Sikar)',
      'Phalodi (Jodhpur)',
      'Dudu (Jaipur)',
      'Beawar (Ajmer)',
      'Didwana-Kuchaman (Nagaur)',
      'Salumber (Udaipur)',
      'Shahpura (Bhilwara)',
      'Jodhpur Urban (Jodhpur)',
      'Jodhpur Rural (Jodhpur)',
      'Balotra (Barmer)',
      'Deeg (Bharatpur)',
      'Jaipur Urban (Jaipur)',
      'Jaipur Rural (Jaipur)',
      'Kekri (Ajmer)',
      'Sanchore (Jalore)',
      'Khairthal (Alwar)',
      'Anupgarh (Sriganganagar)',
      'Gangapur City (Sawai Madhopur)',
      'Neem ka thana (Sikar)',
      'Phalodi (Jodhpur)',
      'Dudu (Jaipur)',
      'Beawar (Ajmer)',
      'Didwana-Kuchaman (Nagaur)',
      'Salumber (Udaipur)',
      'Shahpura (Bhilwara)',
    ];

    List<String> applicableActs = [
      'Act A, Act B',
      'Act C, Act D',
      'Act E, Act F',
      'Act G, Act H',
      'Act I, Act J',
      'Act K, Act L',
      'Act M, Act N',
      'Act O, Act P',
      'Act Q, Act R',
      'Act S, Act T',
      'Act U, Act V',
      'Act W, Act X',
      'Act Y, Act Z',
      'Act AA, Act BB',
      'Act CC, Act DD',
      'Act EE, Act FF',
      'Act GG, Act HH',
      'Act II, Act JJ',
      'Act KK, Act LL',
      'Act MM, Act NN',
      'Act OO, Act PP',
      'Act QQ, Act RR',
      'Act SS, Act TT',
      'Act UU, Act VV',
      'Act WW, Act XX',
      'Act YY, Act ZZ',
      'Act AAA, Act BBB',
      'Act CCC, Act DDD',
      'Act EEE, Act FFF',
      'Act GGG, Act HHH',
      'Act III, Act JJJ',
      'Act KKK, Act LLL',
      'Act MMM, Act NNN',
      'Act OOO, Act PPP',
      'Act QQQ, Act RRR',
      'Act SSS, Act TTT',
      'Act UUU, Act VVV',
      'Act WWW, Act XXX',
      'Act YYY, Act ZZZ',
      'Act AAAA, Act BBBB',
      'Act CCCC, Act DDDD',
      'Act EEEE, Act FFFF',
      'Act GGGG, Act HHHH',
      'Act IIII, Act JJJJ',
      'Act KKKK, Act LLLL',
      'Act MMMM, Act NNNN',
      'Act OOOO, Act PPPP',
      'Act QQQQ, Act RRRR',
      'Act SSSS, Act TTTT',
      'Act UUUU, Act VVVV',
    ];

    if (indianNames.length != rajasthanDistricts.length ||
        indianNames.length != applicableActs.length) {
      throw Exception("Lists should have the same length");
    }

    return Scaffold(
      appBar: AppBar(
        title: Text('CCTNS Database'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: DataTable(
            headingRowColor:
                MaterialStateColor.resolveWith((states) => Colors.blue),
            columnSpacing: 16.0,
            columns: [
              DataColumn(
                label: Container(
                  width: 150,
                  child: Text('Name of Candidate',
                      style: TextStyle(color: Colors.white)),
                ),
              ),
              DataColumn(
                label: Container(
                  width: 150,
                  child: Text('Applicable Acts',
                      style: TextStyle(color: Colors.white)),
                ),
              ),
              DataColumn(
                label: Container(
                  width: 150,
                  child:
                      Text('District', style: TextStyle(color: Colors.white)),
                ),
              ),
            ],
            rows: List.generate(rajasthanDistricts.length, (index) {
              return DataRow(cells: [
                DataCell(
                    Container(width: 150, child: Text(indianNames[index]))),
                DataCell(
                    Container(width: 150, child: Text(applicableActs[index]))),
                DataCell(Container(
                    width: 150, child: Text(rajasthanDistricts[index]))),
              ]);
            }),
          ),
        ),
      ),
    );
  }
}
